### ISSUE TITLE
I'm getting this error "/usr/include/X11/Xft/Xft.h fatal error: ft2build.h: No such file or directory"

### ISSUE THREAD

**Issue by daedmaet187** [AdamYuan/dwm-winicon#4]
I'm applying winicon manually, after adding vanitygaps, pertag, swallow, systray patches.

distro: arch linux

![2022-01-23-011117_1117x508_scrot](https://user-images.githubusercontent.com/23425032/150657151-54f914eb-df81-4b73-8ede-af12cff0f2ca.png)

**Comment by AdamYuan** [comment]
I don't think it's my fault.
Obviously the FreeType2 include path (for example, -I/usr/include/freetype2) is missing in your CFLAGS. So please check the INCS variable in your config.mk.

**Comment by daedmaet187** [comment]
I'm sorry if I'm bothering you with this, but I'm a bit frustrated about it. It's already included in the cflags, this is my config.mk file.
![2022-01-23-133629_2560x1080_scrot](https://user-images.githubusercontent.com/23425032/150674675-ca8420e2-c5f5-4a77-830d-57f110f4e81f.png)

**Comment by daedmaet187** [comment]
I just noticed that I removed the 'I' from the INCS variable by mistake...
Thank you for pointing out the "INCS" in your comment otherwise I wouldn't even notice it. Sorry for wasting your time.
